- name: installing mysql if it is redhat
  hosts: web
  become: yes
  tasks:
   - name: installing mysql if it is redhat
     ansible.builtin.package:
       name: mysql
       state: present
     when: ansible_os_family=="RedHat"   