---
- name: Using variables
  hosts: web
  vars_prompt:
    - name: "name"
      prompt: "Enter a name"
      private: no  # Set to yes if you want to hide the input

  tasks:
    - name: Passing variables
      ansible.builtin.debug:
        msg: "{{ name }}"
