- name: adding user
  hosts: web
  become: yes
  tasks:
   - name: adding user
     ansible.builtin.command: id expense
     register: user
     ignore_errors: yes

   - name: printing
     ansible.builtin.debug:
       msg: "{{user}}"

   - name: adding user
     ansible.builtin.command: useradd expense
     when: user.rc !=0     


   