- name: using for loop
  hosts: web
  become: yes
  tasks: 
   - name:  using for
     ansible.builtin.package:
       name: "{{item}}"
       state: present
     loop:
      - nginx
      - mysql
      - docker  