    - name: Install MySQL Server
      hosts: backend
      become: yes  # Use become to gain root privileges if necessary
      tasks:
      - name: disable nodejs
    
        ansible.builtin.command: dnf module disable nodejs -y

      - name: enable nodejs
    
        ansible.builtin.command: dnf module enable nodejs:20 -y


      - name: Install MySQL Server
        ansible.builtin.package:
         name: nodejs  # Change this to 'mariadb-server' if you're using MariaDB
         state: present 

      - name: Ensure the user expense is present
        ansible.builtin.user:
         name: expense
         state: present   


      - name: Ensure the directory /path/to/directory exists
        ansible.builtin.file:
         path: /app # Replace with your desired directory path
         state: directory    


      - name: Download a file from a URL
        ansible.builtin.get_url:
         url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip # Replace with your file URL
         dest: /tmp/backend.zip


      - name: Unzip a file
        ansible.builtin.unarchive:
         src:  /tmp/backend.zip      # Path to the zip file
         dest: /app    # Directory where the contents will be extracted
         remote_src: yes     