
- name: Install MySQL Server
  hosts: mysql
  become: yes  # Use become to gain root privileges if necessary
  tasks:
    - name: Install MySQL Server
      ansible.builtin.package:
        name: mysql-server  # Change this to 'mariadb-server' if you're using MariaDB
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysqld  # Change this to 'mariadb' if using MariaDB
        state: started
        enabled: yes

     - name: Install the requests package
       ansible.builtin.pip:
        name:  PyMySQL
        state: present    

    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
       login_host: mysql.daws83s.shop
       login_user: root
       login_password: ExpenseApp@1
      register: user
      ignore_errors: yes

    - name: Display a simple debug message
      ansible.builtin.debug:
        msg: "{{user}}"


      

    
    
